### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by calcium840mg** [calcium840mg/furima-36132#13]
# URL
https://furima-36132.herokuapp.com/

# Basic認証のIDとパスワード
Basic認証のID:padolly
パスワード:padolly

# 出品者用のメールアドレスとパスワード
出品者用のメールアドレス:tanaka@tanaka
パスワード:tanaka01

# 購入者用のメールアドレスとパスワード
購入者用のメールアドレス:naoki@naoki
パスワード:naoki02

**Comment by takumi0530** [comment]
@calcium840mg さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
全ての情報を埋めて購入を押すとエラーページに遷移してしまいます。
**※上記により、購入機能と売却後の動作確認ができておりません。次回ご提出時に確認させていただきます。**
<img width="609" alt="スクリーンショット 2021-08-02 17 54 36" src="https://user-images.githubusercontent.com/76197191/127833400-2f2278d4-026b-4ae8-bc4a-cdc0654d5483.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by calcium840mg** [comment]
修正しました。

**Comment by takumi0530** [comment]
@calcium840mg さん、お待たせいたしました。再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/127942193-9e530792-419e-43ca-b658-3a1cc476a55c.png)
